import '@coinbase/onchainkit/styles.css';
import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import { OnchainKitProvider } from '@/providers/OnchainKitProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
  description: 'Generated by `create-onchain`, a Next.js template for OnchainKit',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="bg-background">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <OnchainKitProvider>
            <Navbar />
            {children}
          </OnchainKitProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
